# NUMPY ARRAY

In [1]:
# what is the difference between list and numpy arraay
# why should i use numpy app development instead of list
# numpy array formation from list and tuple
# operations on numpy arrays
# slicing in numpy array
# difference between list slicing and np array slicing 
# arrays functions 
# np.arrange,vstack,hstack 

In [2]:
# numpy is a python module we use it for mathematical and scientific calculation

In [1]:
%%capture timeit_result
import numpy as np
l = [1,2,3,4] # this is the list
l1 = [5,6,7,8]

%timeit sum_list = [i+j for i,j in zip (l,l1)]


ar1 = np.array(l)
ar2 = np.array(l1)

%timeit sum_array = ar1 + ar2

In [2]:
print timeit_result

1000000 loops, best of 3: 887 ns per loop
The slowest run took 51.04 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 512 ns per loop



# so here we prove that numpy aray is so much fast than list and in a list there is only 9 functions was there but in numpy array we ahve some hige no of functions 


In [1]:
l = [range(5),range(10)]

In [2]:
l

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [3]:
# this is basically a two dimensional array



In [4]:
#numpy array only takes homogenous type of element that is only same type of element

In [6]:
import numpy as np 
ar1 = np.array(range(10))

In [7]:
print ar1

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# this is how we make array in python this is so easy to do so

In [9]:
# i have to accept my defeat from now and start becoming chill and start


In [10]:
print type(ar1)

<type 'numpy.ndarray'>


In [11]:
ar2 = np.array((23,45,67))

In [12]:
print ar2


[23 45 67]


In [13]:
print type(ar2)

<type 'numpy.ndarray'>


In [20]:
ar3 = np.array([30,34,43354,45,67,8,3,45,56,78])

In [21]:
print ar3

[   30    34 43354    45    67     8     3    45    56    78]


In [22]:
# lets see numpy array \is mutable or immotable 

In [23]:
ar4 = np.array((23,45,67))

In [24]:
ar4[0] = 10.23

In [25]:
print ar4



[10 45 67]


In [26]:
# see the value is cahnged and from this we can say that numpy array is mutable

In [27]:
ar4.dtype

dtype('int32')

# we can also check what data type int has

In [31]:
np.array(['1','2','3','5'])

array(['1', '2', '3', '5'], dtype='|S1')

In [32]:
# see numpy array can take any of the data type which is homogenous

In [33]:
np.array([1,2,4.5,67])

array([ 1. ,  2. ,  4.5, 67. ])

# if we want to give only one data type we can do this through providing dtype whether int float string at the time of creation of string 

In [34]:
ar5 = np.array([2,3,4,56,767,8989,785654,56.4],dtype = "string")

In [35]:
print ar5

['2' '3' '4' '56' '767' '8989' '785654' '56.4']


In [36]:
# operation on list


In [37]:
ar1 = np.array(range(10))

In [45]:
print ar1
ar1

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
print ar1.size
ar1.size
# we can also check the size

10


10

In [41]:
print ar1.ndim
# we can also check the dimension

1


In [47]:
print ar1.shape
ar1.shape

(10L,)


(10L,)

In [48]:
print ar1.item
ar1.item

<built-in method item of numpy.ndarray object at 0x0000000006F41170>


<function item>

In [44]:
print ar1.itemsize
ar1.items

4


In [49]:
print ar1.reshape(2,5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [51]:
print  ar1.itemsize

4


In [ ]:
# here what i am doing this is i am gtting over these numpy arrays
